theme: jekyll-theme-minimal
browser_tab_title: Sarah Caulfield CV
author: Sarah Caulfield
job_title: Software Engineer
description: Hard-working, proactive, and diligent, with top academic results. I thrive on opportunities to learn, improve and innovate. I enjoy finding ways to make applications and processes more efficient.
css:
  - "/assets/css/style.css"
  - "/assets/css/common.css"
  - "/assets/css/dark-mode.css"
  - "/assets/css/light-mode.css"
js:
  - "/assets/js/scale.fix.js"
  - "/assets/js/enable-dark-mode.js"
